# Generated by Django 3.0.2 on 2020-03-01 18:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FindTutors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='TUser_recipient', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='request',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='TUser_sender', to=settings.AUTH_USER_MODEL),
        ),
    ]
