# Generated by Django 3.0.3 on 2020-02-24 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FindTutors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='biguser',
            name='subjects',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='biguser',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
