# Generated by Django 3.0.3 on 2020-03-02 22:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FindTutors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pictures')),
                ('year', models.CharField(choices=[('1st', 'First Year'), ('2nd', 'Second Year'), ('3rd', 'Third Year'), ('4th', 'Fourth Year')], default='1st', max_length=3)),
                ('user_type', models.CharField(choices=[('1st', 'Tutor'), ('2nd', 'Tutee'), ('3rd', 'Tutor and Tutee')], default='tutor', max_length=15)),
                ('subjects', models.CharField(default='', max_length=500)),
                ('bio', models.TextField(default=' ')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
