# Generated by Django 3.0.3 on 2020-04-14 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FindTutors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='latitute',
            field=models.FloatField(default=38.03646),
        ),
        migrations.AddField(
            model_name='room',
            name='longitude',
            field=models.FloatField(default=-78.50608),
        ),
    ]
