# Generated by Django 3.0.3 on 2020-04-14 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FindTutors', '0002_auto_20200414_1830'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='latitute',
            new_name='latitude',
        ),
    ]
