# Generated by Django 3.0.2 on 2020-04-01 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FindTutors', '0002_auto_20200330_1247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='rating',
        ),
    ]
