# Generated by Django 3.0.3 on 2020-03-02 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FindTutors', '0002_userprofile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfile',
            new_name='Profile',
        ),
    ]
