# Generated by Django 3.0.2 on 2020-03-31 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FindTutors', '0002_auto_20200330_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tuser',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='tutor_profile'),
        ),
    ]
