# Generated by Django 3.0.3 on 2020-02-29 16:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('FindTutors', '0003_request'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='biguser',
            options={},
        ),
        migrations.AlterModelManagers(
            name='biguser',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='biguser',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='biguser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='biguser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='biguser',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='biguser',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='biguser',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='biguser',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='biguser',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='biguser',
            name='password',
        ),
        migrations.RemoveField(
            model_name='biguser',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='biguser',
            name='username',
        ),
        migrations.AddField(
            model_name='biguser',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='request',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='BigUser_recipient', to='FindTutors.BigUser'),
        ),
        migrations.AlterField(
            model_name='request',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='BigUser_sender', to='FindTutors.BigUser'),
        ),
    ]
