# Generated by Django 3.0.2 on 2020-03-01 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FindTutors', '0003_tuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='tuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tuser',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tuser',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
