# Generated by Django 3.0.2 on 2020-04-02 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FindTutors', '0003_auto_20200401_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tuser',
            name='image',
            field=models.ImageField(default='default.png', upload_to='tutor_profile'),
        ),
    ]
