# Generated by Django 3.0.3 on 2020-04-07 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FindTutors', '0003_auto_20200405_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('1st year', 'Tutor'), ('2nd year', 'Tutee'), ('3rd year', 'Tutor and Tutee')], default='tutor', max_length=15),
        ),
        migrations.AlterField(
            model_name='profile',
            name='year',
            field=models.CharField(choices=[('1st year', 'First Year'), ('2nd year', 'Second Year'), ('3rd year', 'Third Year'), ('4th year', 'Fourth Year')], default='1st year', max_length=10),
        ),
    ]
