# Generated by Django 3.0.3 on 2020-04-14 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FindTutors', '0003_auto_20200414_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='request',
            name='longitude',
            field=models.FloatField(default=0),
        ),
    ]
