# Generated by Django 3.0.2 on 2020-03-31 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FindTutors', '0004_auto_20200331_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tuser',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='FindTutors/media/tutor_profile'),
        ),
    ]
