# Generated by Django 3.0.3 on 2020-04-15 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FindTutors', '0004_auto_20200414_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='latitude',
            field=models.FloatField(default=38.03646),
        ),
        migrations.AlterField(
            model_name='request',
            name='longitude',
            field=models.FloatField(default=-78.50608),
        ),
    ]
