# Generated by Django 3.0.3 on 2020-02-29 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FindTutors', '0004_auto_20200229_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='BigUser_recipient', to='FindTutors.BigUser'),
        ),
        migrations.AlterField(
            model_name='request',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='BigUser_sender', to='FindTutors.BigUser'),
        ),
    ]
