# Generated by Django 3.0.2 on 2020-04-02 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FindTutors', '0004_auto_20200401_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='rating',
            field=models.CharField(choices=[('0', 'No Rating'), ('1', 'One Star'), ('2', 'Two Stars'), ('3', 'Three Stars'), ('4', 'Four Stars'), ('5', 'Five Stars')], default='0', max_length=3),
        ),
        migrations.AlterField(
            model_name='tuser',
            name='image',
            field=models.ImageField(default='tutor_profile/default.png', upload_to='tutor_profile'),
        ),
    ]
