# Generated by Django 3.0.3 on 2020-04-08 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FindTutors', '0005_auto_20200407_1910'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorPosting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('image', models.ImageField(default='image3.PNG', upload_to='tutor_profile/')),
                ('phone_number', models.IntegerField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('subjects', models.CharField(default='', max_length=500)),
                ('bio', models.TextField(default=' ')),
                ('user_type', models.PositiveIntegerField(choices=[(1, 'Tutor'), (2, 'Tutee'), (3, 'Tutor and Tutee')], default=1)),
            ],
        ),
    ]
