# Generated by Django 3.0.3 on 2020-04-15 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FindTutors', '0005_auto_20200414_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tuser',
            name='username',
            field=models.CharField(max_length=200),
        ),
    ]
