# Generated by Django 3.0.2 on 2020-03-19 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FindTutors', '0005_tutorprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TutorProfile',
        ),
    ]
