# Generated by Django 3.0.3 on 2020-04-15 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FindTutors', '0006_auto_20200414_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tuser',
            name='subjects',
            field=models.CharField(choices=[('Computer Science', 'Computer Science'), ('Biology', 'Biology'), ('Chemistry', 'Chemistry'), ('Physics', 'Physics'), ('Math', 'Math'), ('English', 'English'), ('Algebra', 'Algebra'), ('Calculus', 'Calculus'), ('Geometry', 'Geometry'), ('Language', 'Language'), ('Reading', 'Reading'), ('Music', 'Music')], max_length=30),
        ),
    ]
