# Generated by Django 3.0.3 on 2020-04-10 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FindTutors', '0006_tutorposting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='subjects',
        ),
        migrations.RemoveField(
            model_name='tutorposting',
            name='subjects',
        ),
        migrations.AddField(
            model_name='profile',
            name='first_major',
            field=models.PositiveIntegerField(choices=[(1, 'African American and African Studies'), (2, 'American Sign Language Program'), (3, 'American Studies'), (4, 'Anthropology'), (5, 'Archaeology'), (6, 'Art'), (7, 'Astronomy'), (8, 'Bioethics'), (9, 'Biology'), (10, 'Chemistry'), (11, 'Classics'), (12, 'Cognitive Science'), (13, 'Comparative Literature'), (14, 'Creative Writing Program'), (15, 'Disability Studies'), (16, 'Drama'), (17, 'East Asian Languages, Literatures & Cultures'), (18, 'Bioethics'), (19, 'Biology'), (20, 'Economics'), (21, 'English'), (22, 'Environmental Sciences'), (23, 'Environmental Thought & Practice'), (24, 'European Studies'), (25, 'French'), (26, 'Global Studies'), (27, 'History'), (28, 'Jewish Studies'), (29, 'Latin American Studies'), (30, 'Linguistics'), (31, 'Mathematics'), (32, 'Media Studies'), (33, 'Medieval Studies'), (34, 'Mellon Indigenous Arts Program'), (35, 'Middle Eastern & South Asian Languages & Cultures'), (36, 'Music'), (37, 'Neuroscience'), (38, 'Philosophy'), (39, 'Physics'), (40, 'Political and Social Thought'), (41, 'Political Philosophy, Policy & Law'), (42, 'Politics'), (43, 'Psychology'), (44, 'Religious Studies'), (45, 'Slavic Languages & Literatures'), (46, 'Sociology'), (47, 'Spanish, Italian & Portuguese'), (48, 'Statistics'), (49, 'Women, Gender & Sexuality'), (50, 'Writing & Rhetoric Program'), (51, 'n/a')], default=1),
        ),
        migrations.AddField(
            model_name='profile',
            name='second_major',
            field=models.PositiveIntegerField(choices=[(1, 'African American and African Studies'), (2, 'American Sign Language Program'), (3, 'American Studies'), (4, 'Anthropology'), (5, 'Archaeology'), (6, 'Art'), (7, 'Astronomy'), (8, 'Bioethics'), (9, 'Biology'), (10, 'Chemistry'), (11, 'Classics'), (12, 'Cognitive Science'), (13, 'Comparative Literature'), (14, 'Creative Writing Program'), (15, 'Disability Studies'), (16, 'Drama'), (17, 'East Asian Languages, Literatures & Cultures'), (18, 'Bioethics'), (19, 'Biology'), (20, 'Economics'), (21, 'English'), (22, 'Environmental Sciences'), (23, 'Environmental Thought & Practice'), (24, 'European Studies'), (25, 'French'), (26, 'Global Studies'), (27, 'History'), (28, 'Jewish Studies'), (29, 'Latin American Studies'), (30, 'Linguistics'), (31, 'Mathematics'), (32, 'Media Studies'), (33, 'Medieval Studies'), (34, 'Mellon Indigenous Arts Program'), (35, 'Middle Eastern & South Asian Languages & Cultures'), (36, 'Music'), (37, 'Neuroscience'), (38, 'Philosophy'), (39, 'Physics'), (40, 'Political and Social Thought'), (41, 'Political Philosophy, Policy & Law'), (42, 'Politics'), (43, 'Psychology'), (44, 'Religious Studies'), (45, 'Slavic Languages & Literatures'), (46, 'Sociology'), (47, 'Spanish, Italian & Portuguese'), (48, 'Statistics'), (49, 'Women, Gender & Sexuality'), (50, 'Writing & Rhetoric Program'), (51, 'n/a')], default=51),
        ),
        migrations.AddField(
            model_name='tutorposting',
            name='first_major',
            field=models.PositiveIntegerField(choices=[(1, 'African American and African Studies'), (2, 'American Sign Language Program'), (3, 'American Studies'), (4, 'Anthropology'), (5, 'Archaeology'), (6, 'Art'), (7, 'Astronomy'), (8, 'Bioethics'), (9, 'Biology'), (10, 'Chemistry'), (11, 'Classics'), (12, 'Cognitive Science'), (13, 'Comparative Literature'), (14, 'Creative Writing Program'), (15, 'Disability Studies'), (16, 'Drama'), (17, 'East Asian Languages, Literatures & Cultures'), (18, 'Bioethics'), (19, 'Biology'), (20, 'Economics'), (21, 'English'), (22, 'Environmental Sciences'), (23, 'Environmental Thought & Practice'), (24, 'European Studies'), (25, 'French'), (26, 'Global Studies'), (27, 'History'), (28, 'Jewish Studies'), (29, 'Latin American Studies'), (30, 'Linguistics'), (31, 'Mathematics'), (32, 'Media Studies'), (33, 'Medieval Studies'), (34, 'Mellon Indigenous Arts Program'), (35, 'Middle Eastern & South Asian Languages & Cultures'), (36, 'Music'), (37, 'Neuroscience'), (38, 'Philosophy'), (39, 'Physics'), (40, 'Political and Social Thought'), (41, 'Political Philosophy, Policy & Law'), (42, 'Politics'), (43, 'Psychology'), (44, 'Religious Studies'), (45, 'Slavic Languages & Literatures'), (46, 'Sociology'), (47, 'Spanish, Italian & Portuguese'), (48, 'Statistics'), (49, 'Women, Gender & Sexuality'), (50, 'Writing & Rhetoric Program'), (51, 'n/a')], default=1),
        ),
        migrations.AddField(
            model_name='tutorposting',
            name='second_major',
            field=models.PositiveIntegerField(choices=[(1, 'African American and African Studies'), (2, 'American Sign Language Program'), (3, 'American Studies'), (4, 'Anthropology'), (5, 'Archaeology'), (6, 'Art'), (7, 'Astronomy'), (8, 'Bioethics'), (9, 'Biology'), (10, 'Chemistry'), (11, 'Classics'), (12, 'Cognitive Science'), (13, 'Comparative Literature'), (14, 'Creative Writing Program'), (15, 'Disability Studies'), (16, 'Drama'), (17, 'East Asian Languages, Literatures & Cultures'), (18, 'Bioethics'), (19, 'Biology'), (20, 'Economics'), (21, 'English'), (22, 'Environmental Sciences'), (23, 'Environmental Thought & Practice'), (24, 'European Studies'), (25, 'French'), (26, 'Global Studies'), (27, 'History'), (28, 'Jewish Studies'), (29, 'Latin American Studies'), (30, 'Linguistics'), (31, 'Mathematics'), (32, 'Media Studies'), (33, 'Medieval Studies'), (34, 'Mellon Indigenous Arts Program'), (35, 'Middle Eastern & South Asian Languages & Cultures'), (36, 'Music'), (37, 'Neuroscience'), (38, 'Philosophy'), (39, 'Physics'), (40, 'Political and Social Thought'), (41, 'Political Philosophy, Policy & Law'), (42, 'Politics'), (43, 'Psychology'), (44, 'Religious Studies'), (45, 'Slavic Languages & Literatures'), (46, 'Sociology'), (47, 'Spanish, Italian & Portuguese'), (48, 'Statistics'), (49, 'Women, Gender & Sexuality'), (50, 'Writing & Rhetoric Program'), (51, 'n/a')], default=51),
        ),
        migrations.AlterField(
            model_name='tuser',
            name='image',
            field=models.ImageField(default='default.png', upload_to='tutor_profile/'),
        ),
    ]
