# Generated by Django 3.0.3 on 2020-04-16 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FindTutors', '0007_auto_20200414_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('Tutor', 'Tutor'), ('Tutee', 'Tutee'), ('Tutor and Tutee', 'Tutor and Tutee')], default=' ', max_length=15),
        ),
    ]
