# Generated by Django 3.0.2 on 2020-03-31 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FindTutors', '0008_auto_20200331_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tuser',
            name='image',
            field=models.ImageField(blank=True, default='/media/default.png', upload_to='media'),
        ),
    ]
