# Generated by Django 3.0.2 on 2020-03-31 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FindTutors', '0010_auto_20200331_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tuser',
            name='image',
            field=models.ImageField(blank=True, upload_to='FindTutors/media/'),
        ),
    ]
