# Generated by Django 3.0.2 on 2020-03-26 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FindTutors', '0011_auto_20200323_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tuser',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
    ]
