# Generated by Django 3.0.3 on 2020-03-29 18:15

from django.db import migrations
import django_google_maps.fields


class Migration(migrations.Migration):

    dependencies = [
        ('FindTutors', '0011_auto_20200323_0837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='location',
        ),
        migrations.AddField(
            model_name='request',
            name='address',
            field=django_google_maps.fields.AddressField(default='164 McCormick Rd, Charlottesville, VA 22903', max_length=200),
        ),
    ]
