# Generated by Django 3.0.3 on 2020-03-29 18:37

from django.db import migrations
import django_google_maps.fields


class Migration(migrations.Migration):

    dependencies = [
        ('FindTutors', '0012_auto_20200329_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='geolocation',
            field=django_google_maps.fields.GeoLocationField(default='', max_length=100),
        ),
    ]
