# Generated by Django 3.0.2 on 2020-03-31 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FindTutors', '0013_auto_20200331_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tuser',
            name='image',
            field=models.ImageField(default='default.png', upload_to='tutor_profile'),
        ),
    ]
