# Generated by Django 3.0.2 on 2020-03-26 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FindTutors', '0013_auto_20200326_1549'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(choices=[('0', 'No Rating'), ('1', 'One Star'), ('2', 'Two Stars'), ('3', 'Three Stars'), ('4', 'Four Stars'), ('5', 'Five Stars')], default='0', max_length=3)),
                ('reviews', models.TextField(default=' ')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FindTutors.Profile')),
            ],
        ),
    ]
