# Generated by Django 3.0.2 on 2020-03-28 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FindTutors', '0014_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='tuser',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='profile_pictures'),
        ),
    ]
